[package]
name = "robot_articulation_control"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
cortex-m = "0.7.7"
nalgebra = "0.33.2"

[lib]
name = "robot_articulation_control"
path = "src/lib.rs"
