[package]
name = "robot_articulation_control"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
cordic = "0.1.5"
cortex-m = "0.7.7"

[lib]
name = "robot_articulation_control"
path = "src/lib.rs"
