name: RAC CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: thumbv7em-none-eabihf

    - name: Install embedded target
      run: rustup target add thumbv7em-none-eabihf

    - name: Build workspace
      run: cargo build --workspace --verbose

    - name: Run tests - Target
      run: cargo test --workspace --exclude rac-core --verbose

    - name: Run tests - Host
      run: cargo test --workspace --exclude rac-core --verbose
